{% set name = "brian2tools" %}
{% set version = "0.2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bfdb2c94193c2e28403f2490cfd78e04ff4ebdb6417f475a1746f78ee4caba0

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - brian2 >=2.0
    - matplotlib >=1.3.1
    - pylems >=0.4.9

test:
  imports:
    - brian2tools
    - brian2tools.plotting
    - brian2tools.nmlexport

  commands:
    - MPLBACKEND=Agg py.test --pyargs brian2tools

  requires:
    - pytest

about:
  home: https://github.com/brian-team/brian2tools
  license: CECILL-2.1
  license_file: LICENSE
  dev_url: https://github.com/brian-team/brian2tools
  doc_url: http://brian2tools.readthedocs.io
  summary: 'Tools for the Brian 2 simulator'
  description: >
    The brian2tools package aims to be a collection of useful tools for simulating spiking
    neural networks with Brian 2 and for analyzing the results from those simulations.

extra:
  recipe-maintainers:
    - mstimberg
    - thesamovar      
